#!/bin/bash

ENDPOINT="http://localhost:8080/save-recipe"
AUTH_HEADER="Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTg1NDY5NjMsImlhdCI6MTc1ODQ2MDU2Mywic3ViIjoiYW1hbmRhYnJvbnNvbjI5QGdtYWlsLmNvbSJ9.xRDjtjG8juDexM-92vCQI8kVLTZ52XU624fq_hRLRkA"
CONTENT_TYPE_HEADER="Content-Type: application/json"

URLS=(
  "https://www.handmadeintheheartland.com/the-best-crockpot-pulled-pork/"
  "https://www.bettycrocker.com/recipes/classic-peanut-butter-blossom-cookies/a3563f6e-96b0-443f-ae0a-53cef4be6db6"
  "https://www.allrecipes.com/recipe/16049/granny-kats-pumpkin-roll/"
  "https://www.plainchicken.com/crock-pot-chicken-gravy/"
  "https://www.wellplated.com/air-fryer-fried-chicken-breast/"
  "https://www.momontimeout.com/best-homemade-baked-mac-and-cheese-recipe/"
  "https://tastysimply.com/baked-creamy-cajun-chicken-mozzarella-penne-pasta/"
  "https://cookinginthemidwest.com/blog/fiesta-chicken-tater-tot-casserole/"
  "https://www.cookingclassy.com/pumpkin-chocolate-chip-cookies/"
  "https://preppykitchen.com/pumpkin-cookies/"
  "https://www.onceuponachef.com/recipes/chicken-quesadillas.html"
  "https://thecozycook.com/slow-cooker-beef-stew/"
  "https://cookingwithkatiecross.com/crockpot-cheesy-rotel-potatoes/"
  "https://cookingwithkatiecross.com/chili-cheese-dogs/"
  "https://cookingwithkatiecross.com/parmesan-crusted-steak-bites/"
  "https://cookingwithkatiecross.com/classic-beef-stew/"
  "https://cookingwithkatiecross.com/crockpot-lasagna-soup/"
  "https://cookingwithkatiecross.com/cowboy-butter-steak-potato-skillet/"
  "https://www.recipetineats.com/oven-baked-chicken-breast/"
  "https://tastesbetterfromscratch.com/peach-cobbler/"
  "https://www.allrecipes.com/recipe/26317/chicken-pot-pie-ix/"
  "https://fantabulosity.com/4th-of-july-cupcakes/"
  "https://www.allrecipes.com/recipe/7478/cinnamon-swirl-bundt-coffee-cake/"
  "https://goldengracekitchen.com/chicken-garlic-parmesan-pasta/"
  "https://preppykitchen.com/oatmeal-chocolate-chip-cookies/"
  "https://www.onceuponachef.com/recipes/fried-chicken-sandwiches.html"
  "https://natashaskitchen.com/banana-bread-recipe-video/"
  "https://cookingcircuit.com/chicken-and-sweet-potato-rice-bowl/"
  "https://kathleenscravings.com/blackstone-flatbread-pizza/"
  "https://www.allrecipes.com/recipe/223538/jeffs-hot-dog-chili/"
  "https://damndelicious.net/2019/04/18/mexican-street-tacos/"
  "https://www.allrecipes.com/recipe/7402/carrot-cake-iii/"
  "https://www.gimmesomeoven.com/no-bake-energy-bites/"
  "https://gimmedelicious.com/popeyes-chicken-sandwich/"
  "https://gimmedelicious.com/5-minute-buffalo-chicken-wraps/"
  "https://www.spendwithpennies.com/banana-chocolate-chip-muffins/"
  "https://gimmedelicious.com/creamy-garlic-parmesan-chicken/"
  "https://thecozycook.com/homemade-french-fries/"
  "https://thecozycook.com/stuffed-chicken-breast/"
  "https://downshiftology.com/recipes/air-fryer-salmon/"
  "https://www.wellplated.com/air-fryer-salmon/"
  "https://www.jocooks.com/recipes/garlic-butter-steak-bites/"
  "https://tastesbetterfromscratch.com/oatmeal-chocolate-chip-cookie-bars/"
  "https://cookingtaste.net/chocolate-chip-oatmeal-bars/"
  "https://lilluna.com/snickerdoodles/"
  "https://www.allrecipes.com/recipe/8296140/butterhorn-dinner-rolls/"
  "https://thefoodcharlatan.com/pumpkin-coffee-cake/"
  "https://www.thechunkychef.com/old-fashioned-easy-apple-crisp/"
  "https://sallysbakingaddiction.com/my-favorite-cornbread/"
  "https://www.allrecipes.com/recipe/13477/double-layer-pumpkin-cheesecake/"
  "https://www.allrecipes.com/recipe/9471/peanut-butter-cup-cookies/"
  "https://www.modernhoney.com/fettuccine-alfredo/"
  "https://sallysbakingaddiction.com/pumpkin-crumb-cake-muffins/"
  "https://cafedelites.com/oven-baked-chicken-breast/"
  "https://tastesbetterfromscratch.com/soft-and-chewy-triple-chocolate-mm-cookies/"
  "https://cookingwithkatiecross.com/creamy-cajun-chicken-alfredo/"
  "https://cookingwithkatiecross.com/creamy-cajun-chicken-rice/"
)

for url in "${URLS[@]}"; do
	printf 'Processing: %s\n' "$url"
	curl --fail --silent --show-error --location "$ENDPOINT" \
	  --header "$CONTENT_TYPE_HEADER" \
	  --header "$AUTH_HEADER" \
	  --data "{\"URL\": \"$url\"}"
	printf '\n'
	sleep 1
done
